name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: arduino/arduino-lint-action
        uses: arduino/arduino-lint-action@v1.0.1
        with:
          verbose: true

